In [1]:
import numpy as np

In [3]:
a = np.ones([2, 3])
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
b = np.ones([2, 1])*2
b

array([[2.],
       [2.]])

In [27]:
np.concatenate((a, b), axis = 1)

array([[1., 1., 1., 2.],
       [1., 1., 1., 2.]])

In [24]:
np.concatenate((a, b), axis = 0)

array([[1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [25]:
np.concatenate((a, b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.]])